### ISSUE TITLE
Minecraft Joypad Mod doesn't work

### ISSUE THREAD

**Issue by qqqZXzz123** [theofficialgman/piston-meta-arm64#1]
Hello, I [downloaded](https://github.com/theofficialgman/lwjgl3-binaries-arm64/raw/lwjgl-2.9.4/jinput-platform-2.0.5-natives-linux.jar) libjinput to play with the [joypad](https://github.com/ljsimin/MinecraftJoypadSplitscreenMod) mod in minecraft 1.12.2 on a device with an arm64 processor. 
But I got an error:
`XInput: Controller object linking error. java.lang.UnsatisfiedLinkError: com.ivan.xinput.natives.XInputNatives.getLoadedLibVersion()I`

How can I solve this problem? Thank you in advance.

**Comment by theofficialgman** [comment]
that mod was tested working 3 years ago https://github.com/ljsimin/MinecraftJoypadSplitscreenMod/issues/51#issuecomment-987547993 after updating to use jinput 2.0.7 https://github.com/theofficialgman/piston-meta-arm64/blob/main/mc-static-json/2.9.4-nightly-20150209.json

this was likely user error since you are manually attempting to use the files linked in the meta repo. Please use the theofficialgman natives within prism launcher or by manually modifying your launcher to use the meta as described in the readme https://github.com/theofficialgman/piston-meta-arm64
